import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bring Memories to life! Use our customisable laser engraving tool",
  description: "Generated by create next app",
  icons: "/logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-800 w-full py-3">
          <div className="flex flex-row items-center gap-1">
            <img src="/logo.png" alt="" className="w-10" />
            <p className="font-semibold font-inter">codeNGrave</p>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
